Implement -hpc at cms- c-rsg plot cronjobs
dmwm/CMSSpark pull request #51
Opened 2021-03-23 19:08 UTC by mrceyhun

fyi @vkuznet 
If everything is fine, I'll add new acronjob to cmsmonit user's acronjobs.
It will be run like:
`/bin/bash $HOME/CMSSpark/bin/cron_hpc_at_cms.sh /eos/user/c/cmsmonit/www/hpc/`

2021-03-23 23:48 UTC, vkuznet requested changes

2021-03-23 23:48 UTC, vkuznet commented on bin/cron_hpc_at_cms.sh
> +START_DATE="${2:-$(date -d "$END_DATE -1 year" +%Y-%m-01)}"
both days should be validated first before passing to the script.

2021-03-23 23:48 UTC, vkuznet commented on bin/cron_hpc_at_cms.sh
> +   - if not END_DATE is specified, it will use the first day of the current month.
you should specify date format script expects

2021-03-23 23:48 UTC, vkuznet commented on bin/run_hpc_at_cms.sh
> +if [ -e "/usr/lib/jvm/java-1.8.0" ]
here you should first check if JAVA_HOME is set in environment and use it. This will allows to move smoothly to next java version

2021-03-23 23:48 UTC, vkuznet commented on bin/cron_hpc_at_cms.sh
> +START_DATE="${2:-$(date -d "$END_DATE -1 year" +%Y-%m-01)}"
I saw later that python script calls the validation. I suggest that you add a comment here in  a script that actual validation will be performed by python script.

2021-03-24 11:07 UTC, mrceyhun commented
@vkuznet I applied the changes.

2021-03-24 16:16 UTC, merged

2021-03-27 02:16 UTC, mrceyhun commented
@vkuznet @leggerf 
acronjob of hpc is added under cmsmonit user.